:source-highlighter: coderay
:classe: 2de
:headerTitle: Informatique
:icons: font


== [underline]#Lancers de dés#

NOTE: Cette activité est une reproduction du TP 3 page 297 du manuel.


. {sp}
.. Reproduire la fonction ci-dessous puis la compléter pour qu’elle renvoie l’effectif d’une valeur d’une liste donnée.
+
[source,python]
----
from random import randint
import matplotlib.pyplot as plt


def nombre_de(valeur, liste):
    nb=0
    for x in liste:
        if x==...:
            ...
    return nb
----
.. Que renvoie `nombre_de(1, [2,1,4,3,1,3,6,1,7,12])` ?
. On considère l'expérience aléatoire suivante : on lance deux dés équilibrés à six faces et on fait la somme des deux faces obtenues.
+
Le programme suivant écrit à la suite de la fonction `nombre_de`, permet de représenter par un nuage de points le nombre d’obtentions de chaque issue lorsqu’on répète 1 000 fois  l’expérience précédente.
+
[source,python]
----
L = [randint(1,6)+randint(1,6) for i in range(1000)]
for k in range(...,...):
    plt.plot(k,nombre_de(k,L),'*')
plt.show()
----
+
.. Compléter ce programme et commenter le graphique obtenu.
.. Modifier ce programme de façon à répéter 10 000 fois l'expérience aléatoire.
.. Modifier ce programme pour qu’il calcule la moyenne des sommes obtenues après 10 000 lancers des deux dés.